"use client";
import {useMemo,useState} from "react";
import {Activity,ArrowDownToLine,Bell,Box,Building2,ChevronDown,ChevronLeft,ChevronRight,CircleDollarSign,ClipboardCheck,FileBarChart,HardHat,Home,LayoutDashboard,Menu,Package,Plus,RefreshCw,Search,Settings,ShieldCheck,Truck,Users,WalletCards,X} from "lucide-react";
import {activities,districts,stateTotals} from "@/lib/demo-data";
import {ExpenseChart,StageChart,StatusChart} from "./charts";
import {TelanganaMap} from "./telangana-map";

const nav=[["Dashboard",LayoutDashboard],["Beneficiaries",Users],["Projects / Sites",Building2],["Construction",HardHat],["Payments",WalletCards],["Expenses",CircleDollarSign],["Inventory",Package],["Purchases",Box],["Material Issues",Truck],["Vendors",Users],["Reports",FileBarChart],["Audit Logs",ShieldCheck],["Settings",Settings]] as const;
const compact=(n:number)=>new Intl.NumberFormat("en-IN",{notation:"compact",maximumFractionDigits:1}).format(n);
const currency=(n:number)=>`₹${n.toLocaleString("en-IN",{maximumFractionDigits:1})} Cr`;

function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={`rounded-2xl border border-slate-200/80 bg-white shadow-[0_1px_2px_rgba(20,30,55,.03)] ${className}`}>{children}</section>}
function Stat({title,value,change,icon:Icon,color}:{title:string;value:string;change:string;icon:typeof Users;color:string}){return <Card className="animate-in p-4"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-slate-500">{title}</p><p className="mt-2 text-[22px] font-bold tracking-tight text-slate-900">{value}</p></div><span className={`rounded-xl p-2.5 ${color}`}><Icon size={18}/></span></div><div className="mt-3 flex items-center gap-1 text-[11px]"><span className="font-semibold text-emerald-600">↗ {change}</span><span className="text-slate-400">vs last month</span></div></Card>}

export function Dashboard(){
 const [selected,setSelected]=useState("all"); const [collapsed,setCollapsed]=useState(false); const [mobile,setMobile]=useState(false); const [notice,setNotice]=useState(4);
 const current=useMemo(()=>districts.find(d=>d.id===selected)||stateTotals,[selected]);
 const stats=[["Total Applications",compact(current.applications),"8.2%",ClipboardCheck,"bg-pink-50 text-pink-700"],["Approved",compact(current.approved),"6.4%",ShieldCheck,"bg-blue-50 text-blue-700"],["Construction Started",compact(current.started),"11.7%",HardHat,"bg-amber-50 text-amber-700"],["Completed Houses",compact(current.completed),"9.8%",Home,"bg-emerald-50 text-emerald-700"],["Funds Released",currency(current.funds),"12.1%",CircleDollarSign,"bg-violet-50 text-violet-700"],["Inventory Value","₹286.4 Cr","4.6%",Package,"bg-cyan-50 text-cyan-700"]] as const;
 return <div className="min-h-screen bg-[#f5f6f8] text-slate-800">
  {mobile&&<button aria-label="Close menu overlay" onClick={()=>setMobile(false)} className="fixed inset-0 z-30 bg-slate-950/30 lg:hidden"/>}
  <aside className={`fixed inset-y-0 left-0 z-40 flex flex-col bg-[#101b31] text-white transition-all ${collapsed?"lg:w-[76px]":"lg:w-[244px]"} ${mobile?"w-[260px] translate-x-0":"w-[260px] -translate-x-full lg:translate-x-0"}`}>
   <div className="flex h-[72px] items-center gap-3 border-b border-white/10 px-5"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#b32662]"><Home size={20}/></div>{!collapsed&&<div><b className="text-sm">INDIRAMMA ILLU</b><p className="text-[9px] tracking-[.14em] text-slate-400">MANAGEMENT TOOL</p></div>}<button onClick={()=>setMobile(false)} className="ml-auto lg:hidden" aria-label="Close navigation"><X/></button></div>
   <nav className="scrollbar-none flex-1 overflow-y-auto p-3" aria-label="Main navigation"><p className={`px-3 pb-2 pt-1 text-[9px] font-bold tracking-[.18em] text-slate-500 ${collapsed?"lg:hidden":""}`}>WORKSPACE</p>{nav.map(([label,Icon],i)=><button key={label} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[13px] transition ${i===0?"bg-[#9c1d52] text-white shadow-lg shadow-pink-950/20":"text-slate-300 hover:bg-white/7 hover:text-white"}`} title={label}><Icon size={18}/>{!collapsed&&<span>{label}</span>}{label==="Expenses"&&!collapsed&&<span className="ml-auto rounded-full bg-amber-400 px-2 text-[9px] font-bold text-slate-900">12</span>}</button>)}</nav>
   <div className="m-3 rounded-xl bg-white/5 p-3">{!collapsed&&<><p className="text-xs font-semibold">Support centre</p><p className="mt-1 text-[10px] leading-4 text-slate-400">Need help managing a record?</p><button className="mt-2 text-[11px] font-semibold text-pink-300">View guide →</button></>}</div>
  </aside>
  <main className={`transition-all ${collapsed?"lg:ml-[76px]":"lg:ml-[244px]"}`}>
   <header className="sticky top-0 z-20 flex h-[72px] items-center gap-3 border-b border-slate-200 bg-white/95 px-4 backdrop-blur md:px-6"><button onClick={()=>setMobile(true)} className="rounded-lg p-2 hover:bg-slate-100 lg:hidden" aria-label="Open navigation"><Menu size={20}/></button><button onClick={()=>setCollapsed(x=>!x)} className="hidden rounded-lg p-2 hover:bg-slate-100 lg:block" aria-label="Collapse sidebar">{collapsed?<ChevronRight size={19}/>:<ChevronLeft size={19}/>}</button><div className="relative hidden max-w-md flex-1 sm:block"><Search className="absolute left-3 top-2.5 text-slate-400" size={17}/><input aria-label="Global search" placeholder="Search beneficiary, project, vendor..." className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-4 text-xs outline-none focus:border-pink-400"/></div><button className="ml-auto rounded-xl border border-slate-200 p-2.5 text-slate-500 hover:bg-slate-50" onClick={()=>setNotice(0)} aria-label="Notifications"><Bell size={18}/>{notice>0&&<span className="absolute -mt-3 ml-2 grid h-4 w-4 place-items-center rounded-full bg-[#b32662] text-[8px] text-white">{notice}</span>}</button><button className="hidden items-center gap-2 rounded-xl bg-[#9c1d52] px-4 py-2.5 text-xs font-semibold text-white hover:bg-[#7f1744] sm:flex"><Plus size={16}/>Quick Add<ChevronDown size={13}/></button><div className="flex items-center gap-2 border-l border-slate-200 pl-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-pink-100 text-xs font-bold text-pink-800">AK</div><div className="hidden md:block"><p className="text-xs font-semibold">Anil Kumar</p><p className="text-[10px] text-slate-400">Super Admin</p></div></div></header>
   <div className="mx-auto max-w-[1600px] p-4 md:p-6">
    <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs text-slate-400">Dashboard / Overview</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-950">Indiramma Illu Management Dashboard</h1><p className="mt-1 text-xs text-slate-500">Beneficiary, Construction, Finance & Resource Monitoring</p></div><div className="flex flex-wrap gap-2"><button className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-medium"><RefreshCw size={14}/>31 Aug 2026, 05:45 PM</button><button className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-medium"><ArrowDownToLine size={14}/>Export</button></div></div>
    <div className="mb-6 grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{stats.map(([a,b,c,d,e])=><Stat key={a} title={a} value={b} change={c} icon={d} color={e}/>)}</div>
    <div className="mb-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><Card><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div><h2 className="text-sm font-bold">Telangana District Performance</h2><p className="mt-1 text-[11px] text-slate-400">Select a district to update all dashboard statistics</p></div><select value={selected} onChange={e=>setSelected(e.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs"><option value="all">Telangana Overall</option>{districts.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><div className="grid md:grid-cols-[1.05fr_.95fr]"><TelanganaMap districts={districts} selected={selected} onSelect={setSelected}/><div className="m-4 rounded-xl bg-slate-50 p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#9c1d52]">Selected region</p><h3 className="mt-1 text-xl font-bold">{current.name}</h3></div><span className="rounded-lg bg-white px-2 py-1 text-[10px] text-slate-500">Live view</span></div><div className="mt-5 grid grid-cols-2 gap-x-6 gap-y-5">{[["Applications",current.applications],["Approved",current.approved],["In Progress",current.progress],["Completed",current.completed],["Pending",current.pending],["Funds",`₹${current.funds} Cr`]].map(([k,v])=><div key={k}><p className="text-[10px] text-slate-400">{k}</p><p className="mt-1 text-base font-bold">{typeof v==="number"?v.toLocaleString("en-IN"):v}</p></div>)}</div>{selected!=="all"&&<button onClick={()=>setSelected("all")} className="mt-6 w-full rounded-lg bg-[#101b31] py-2.5 text-xs font-semibold text-white">View Telangana Overall</button>}</div></div></Card><Card className="p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold">Application Status</h2><p className="mt-1 text-[11px] text-slate-400">Current scheme distribution</p></div><button className="text-[11px] font-semibold text-[#9c1d52]">View report</button></div><StatusChart/><div className="grid grid-cols-2 gap-2">{[["Completed","#178760"],["In progress","#3979dc"],["Approved","#9c1d52"],["Pending","#e6a23c"]].map(([n,c])=><div key={n} className="flex items-center gap-2 text-[11px] text-slate-500"><i className="h-2 w-2 rounded-full" style={{background:c}}/>{n}</div>)}</div></Card></div>
    <div className="mb-6 grid gap-6 lg:grid-cols-2"><Card className="p-5"><div className="mb-4"><h2 className="text-sm font-bold">Construction Progress</h2><p className="text-[11px] text-slate-400">Completion by construction stage (%)</p></div><StageChart/></Card><Card className="p-5"><div className="mb-4 flex justify-between"><div><h2 className="text-sm font-bold">Monthly Expenses</h2><p className="text-[11px] text-slate-400">Fund utilization trend in crores</p></div><span className="text-xs font-bold text-emerald-600">+12.6%</span></div><ExpenseChart/></Card></div>
    <Card className="mb-6 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="text-sm font-bold">District Performance</h2><p className="mt-1 text-[11px] text-slate-400">Applications, construction and fund utilization</p></div><button className="text-xs font-semibold text-[#9c1d52]">View all 33 districts →</button></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr>{["District","Applications","Approved","Construction started","Completed","Completion","Funds released",""].map(h=><th key={h} className="px-5 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{districts.slice(0,5).map(d=><tr key={d.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-5 py-3.5 font-semibold">{d.name}</td><td className="px-5 py-3.5">{d.applications.toLocaleString("en-IN")}</td><td className="px-5 py-3.5">{d.approved.toLocaleString("en-IN")}</td><td className="px-5 py-3.5">{d.started.toLocaleString("en-IN")}</td><td className="px-5 py-3.5 font-semibold text-emerald-700">{d.completed.toLocaleString("en-IN")}</td><td className="px-5 py-3.5"><div className="flex items-center gap-2"><div className="h-1.5 w-20 rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{width:`${d.completed/d.applications*100}%`}}/></div>{Math.round(d.completed/d.applications*100)}%</div></td><td className="px-5 py-3.5">₹{d.funds} Cr</td><td className="px-5 py-3.5"><button onClick={()=>setSelected(d.id)} className="font-semibold text-[#9c1d52]">View</button></td></tr>)}</tbody></table></div></Card>
    <div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><Card><div className="border-b border-slate-100 p-5"><h2 className="text-sm font-bold">Recent Activities</h2><p className="mt-1 text-[11px] text-slate-400">Latest updates across the program</p></div><div>{activities.map((a,i)=><div key={a[2]} className="flex items-center gap-4 border-b border-slate-100 px-5 py-3.5 last:border-0"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${i%2?"bg-blue-50 text-blue-600":"bg-pink-50 text-pink-700"}`}><Activity size={15}/></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{a[0]} <span className="font-normal text-slate-500">· {a[1]}</span></p><p className="mt-1 text-[10px] text-slate-400">{a[2]}</p></div><time className="text-[10px] text-slate-400">{a[3]}</time></div>)}</div></Card><Card className="p-5"><div className="flex justify-between"><div><h2 className="text-sm font-bold">Inventory Alerts</h2><p className="mt-1 text-[11px] text-slate-400">Items requiring attention</p></div><span className="rounded-full bg-red-50 px-2 py-1 text-[10px] font-bold text-red-600">8 alerts</span></div><div className="mt-5 space-y-3">{[["Cement OPC 53","12 bags","Low stock"],["TMT Steel 12mm","0 kg","Out of stock"],["Exterior Paint","18 L","Low stock"],["PVC Pipes 4 inch","24 pcs","Low stock"]].map((x,i)=><div key={x[0]} className="flex items-center rounded-xl border border-slate-100 p-3"><span className={`mr-3 h-9 w-1 rounded-full ${i===1?"bg-red-500":"bg-amber-400"}`}/><div className="flex-1"><p className="text-xs font-semibold">{x[0]}</p><p className="mt-1 text-[10px] text-slate-400">Available: {x[1]}</p></div><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${i===1?"bg-red-50 text-red-600":"bg-amber-50 text-amber-700"}`}>{x[2]}</span></div>)}</div></Card></div>
    <footer className="mt-8 flex flex-col justify-between gap-2 border-t border-slate-200 py-5 text-[10px] text-slate-400 sm:flex-row"><span>© 2026 EESHA INFRA GLOBAL PRIVATE LIMITED</span><span>Indiramma Illu Management Tool · Version 1.0.0</span></footer>
   </div>
  </main>
 </div>
}
